monolog:
    handlers:
        filter_for_errors:
            type: fingers_crossed
            action_level: notice
            handler: file_log

        file_log:
            type: rotating_file
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            max_files: 7

        syslog_handler:
            type: syslog
            level: error