add_to_black_list: "Визит успешно добавлен в БЛ"
add_to_black_list_error: "Ошибка при добавлении визита в БЛ"
add_to_black_list_counter: "Добавлено в БЛ %s из %s"
add_to_white_list: "Визит успешно добавлен в ВЛ"
add_to_white_list_error: "Ошибка при добавлении визита в ВЛ"
black_list_delete: "Визит удален из БЛ"
black_list_delete_error: "Ошибка удаления визита из БЛ"
black_list_delete_counter: "Удалено визитов из БЛ %s из %s"
conversion_add: "Конверсия успешно добавлена"
conversion_edit: "Редактирование конверсии прошло успсешно"
conversion_action_is_not_click_error: "В системе отсуствует информация о клике %s"
conversion_action_click_has_conversion: "Данная конверсия уже есть в системе"
conversion_delete: "Конверсия удалена"
conversion_delete_error: "Ошибка при удалении конверсии: %s"
news_category_add: "Категория успешно добавлена"
news_category_add_error: "При добавлении категораии произошла ошибка"
news_category_edit: "Категория успешно отредактирована"
news_category_edit_error: "При редактировании категории произошла ошибка"
news_delete: "Новость удалена"
news_delete_error: "Ошибка при удалении новости: %s"
basic_settings_edit: "Основные настройки успешно отредактированы"
user_create: "Пользователь успешно создан"
user_create_error: "При создании пользователя произошла ошибка"
user_edit_password: "Пароль успешно изменен"
user_edit: "Пользователь успешно отредактирован"
user_edit_error: "При редактировании пользователя произошла ошибка"
user_login_inactive_error: "Пользователь неактивен"
user_login_auth_error: "Ошибка авторизации"
user_settings_update_error: "Ошибка обновления настроек пользователя"
domain_create: "Домен успешно добавлен"
domain_edit: "Редактирование прошло успешно"
domain_delete: "Домен удален"
domain_delete_is_main_error: "Нельзя удалить основной домен"
news_edit: "Редактирование прошло успешно"
news_create: "Новость успешно добавлена"
news_copy: "Новость скопирована"
news_create_teasers_blocked: "В список заблокированных были добавлены тизеры - %s"
news_create_teasers_blocked_error: "В список заблокированных не были были добавлены тизеры - %s, т.к. не существуют"
news_create_sources_blocked: "В список заблокированных были добавлены источники - %s"
news_create_sources_blocked_error: "В список заблокированных не были добавлены источники - %s, т.к. не существуют"
partner_delete: "Партнерка удалена"
settings_edit_password: "Пароль изменен"
settings_edit: "Настройки изменены"
source_create: "Источник создан"
source_create_error: "При добавлении источника произошла ошибка"
source_edit: "Источник изменён"
source_edit_error: "При изменении источника произошла ошибка"
source_delete: "Источник удален"
source_delete_error: "Ошибка при удалении источника: %s"
teasers_groups_mass_delete: "Удалены следующие %s - %s"
teasers_sub_groups_save_and_redirect: "Подгруппы %s %s"
teasers_groups_save_and_redirect: "Группы %s %s"
teasers_groups_mass_delete_error: "Нельзя удалить следующие группы - %s. Сперва удалите их подгруппы"
teasers_sub_groups_mass_delete_error: "Нельзя удалить следующие подгруппы - %s. Сперва удалите или переместите их тизеры"
teaser_groups_delete: "Группа удалена."
teaser_groups_delete_error: "Ошибка при удалении группы: %s"
teaser_groups_delete_has_sub_groups_error: "Нельзя удалить группу. Сперва удалите ее подгруппы."
teaser_edit: "Тизер успешно отредактирован"
teaser_create: "Тизер успешно добавлен"
teaser_delete: "Тизер удален"
teaser_copy: "Тизер скопирован"
teaser_copy_error: "Ошибка при копировании тизера"
country_edit: "Страна успешно отредактирована"
country_edit_error: "При редактировании страны произошла ошибка"
country_delete: "Страна удалена"
country_delete_error: "Невозможно удалить страну. Она используется в тизерах или новостях"
domain_active_old_domain_deactivate: "Старый домен деактивирован"
domain_active_deactivated: "%s деактивирован"
domain_active_activated: "%s активирован"
teasers_mass_blocked_list: "Актуальный список заблокированных тизеров - %s"
teasers_mass_blocked_list_error: "В список заблокированных не были были добавлены тизеры - %s т.к. не существуют"
sources_mass_blocked_list: "Актуальный список заблокированных источников - %s"
sources_mass_blocked_list_error: "В список заблокированных не были были добавлены источники - %s т.к. не существуют"
news_mass_blocked_list: "Актуальный список заблокированных новостей - %s"
news_mass_blocked_list_error: "В список заблокированных не были добавлены новости - %s, т.к. не существуют"
teasers_sub_group_create: "Подгруппа успешно добавлена"
teasers_sub_group_delete: "Подгруппа удалена"
teasers_sub_group_delete_error: "Нельзя удалить подгруппу. Сперва удалите или переместите ее тизеры."
teasers_sub_group_edit: "Подгруппа успешно отредактирована"
mediabuyer_news_delete_is_not_author_error: "Нельзя удалить новости - %s так как вы не их автор."
costs_edit: "Расход успешно отредактирован"
costs_delete: "Расходы удалены"
costs_edit_error: "При редактировании расхода произошла ошибка"
costs_delete_error: "Не удалось удалить расходы - %s"
cost_add_over_date_range_error: "Период должен быть не более месяца"
cost_add_date_from_greater_than_date_to_error: "Дата начала не может превышать дату окончания"
cost_add_added: "Расход(ы) добавлены %d из %d"
cost_exists: "Расход с параметрами %s %s %s уже существует"
white_list_delete: "Визит удален из ВЛ"
white_list_delete_error: "Ошибка удаления визита из ВЛ"
add_to_white_list_counter: "Добавлено в ВЛ %s из %s"
white_list_delete_counter: "Удалено визитов из ВЛ %s из %s"
